// Refresh fixtures (E2, the locked sketch qwry-agent-lab/docs/refresh-sketch-e2.html).
// The refresh harness is the FIRST to frame the whole window rather than one
// card's face: ⌘R and ⇧⌘R are shell-wide acts, and a sweep that crosses the
// sidebar, the main card and the inspector cannot be evidenced inside any one
// of them. So these seeds fill every store the shell reads (connections, tabs,
// schema, browser, results, edits, inspector, side pane, canvas) and
// RefreshHarness composes the real `.v2-shell` around them.
//
//   e2-table         a browse tab on public.users, 14 rows, the 4th selected
//                    in the inspector, the sketch's `hard-ok` scenario
//   e2-table-staged  the same tab with 3 staged edits: its main body must NOT
//                    refetch (R4), so the frame's evidence is the rows still
//                    standing under a sweep that crossed them
//   e2-query         a read-only SELECT with its rows: every executed head is
//                    read-only, so the tab reruns
//   e2-query-wrote   the same tab after an UPDATE: `OK · 1 row affected`, the
//                    rows stay and the status bar says why (R4)
//   e2-canvas        two result widgets, a note, a third result widget: the
//                    widgets refetch in the order the sweep's front reaches
//                    them and the note never does
//   e2-dead          session_probe answers false and connect rejects, so the
//                    sweep plays over surfaces that never cycle (R6)
//
// The row data is the sketch's own, generated by the sketch's own expressions
// rather than transcribed, and the browse SQL comes from the product's
// `browseSql`, so `executedSql` is exactly what a refresh run re-executes.

import type { ColumnMeta, Profile, StatementResult } from "../ipc/types";
import type { Block, CanvasDoc, CanvasMeta, ResultBlock } from "../stores/canvas";
import type { SchemaSnapshot, TableInfo } from "../stores/schema";
import { browseSql, keysetKeys } from "../stores/browseSql";
import type { Tab } from "../stores/tabs";

export const E2_STATES = [
  "e2-table",
  "e2-table-staged",
  "e2-query",
  "e2-query-wrote",
  "e2-canvas",
  "e2-dead",
] as const;
export type E2State = (typeof E2_STATES)[number];

/** the window's own three widths: the main card's floor, its default, a wide
 * window. The sketch drops the inspector at 640 and narrows it at 960 */
export const E2_WIDTHS = [640, 960, 1280] as const;

/** the window in every frame, the sketch's own `.shell` height */
export const E2_CARD_H = 640;

/** the pane at each width: closed at the floor (the sketch's `.w640 .right`),
 * the sketch's 250 at 960 and the product's own default at 1280 */
export const E2_PANE_W: Record<number, number | null> = { 640: null, 960: 250, 1280: 300 };

export const E2_PROFILE_ID = "harness-staging";
export const E2_TABLE_TAB = "e2-tab-users";
export const E2_QUERY_TAB = "e2-tab-query";
export const E2_CANVAS_TAB = "e2-tab-canvas";
export const E2_CANVAS_ID = "e2-canvas-1";
export const E2_SESSION = "e2-session";

/** the sketch's simulated round trips, which its timeline was drawn from: the
 * tree lands at 700, the rows at 900, the inspector's cell at 500. The shim
 * answers on these unless a `lat` param overrides them */
export const E2_LAT = { tree: 700, rows: 900, cell: 500 } as const;

export const isE2State = (s: string): s is E2State =>
  (E2_STATES as readonly string[]).includes(s);

// ---- the connection --------------------------------------------------------

export const e2Profile: Profile = {
  id: E2_PROFILE_ID,
  name: "auth_new",
  host: "staging-db.internal",
  port: 5432,
  dbname: "auth_new",
  user: "qwry_ro",
  sslmode: "require",
  color: "#a970ff",
  glyph: null,
  is_prod: false,
};

// ---- the schema ------------------------------------------------------------

const TS = "timestamp with time zone";

const col = (
  name: string,
  type: string,
  attnum: number,
  notNull = false,
): TableInfo["columns"][number] => ({
  name,
  attnum,
  type,
  type_oid: 0,
  not_null: notNull,
  default: null,
});

const table = (oid: number, name: string, columns: TableInfo["columns"], reltuples: number): TableInfo => ({
  table_oid: oid,
  schema: "public",
  name,
  kind: "r",
  columns,
  pk: ["id"],
  has_children: false,
  reltuples,
  comment: null,
  parent_oid: null,
});

const id = col("id", "bigint", 1, true);
const createdAt = col("created_at", TS, 9);

export const E2_USERS: TableInfo = table(
  16_001,
  "users",
  [
    id,
    col("email", "text", 2),
    col("name", "text", 3),
    col("is_onboarded_on_app", "boolean", 4),
    createdAt,
    col("phone", "text", 5),
    col("oauth_provider", "text", 6),
  ],
  842_113,
);

/** the sketch's twelve tables, in its own order and with its own estimates */
const OTHERS: [string, number][] = [
  ["sessions", 2_214_090],
  ["wardrobes", 118_402],
  ["wardrobe_products_v2", 9_401_211],
  ["product_votes", 3_120_044],
  ["orders", 77_120],
  ["order_items", 164_338],
  ["carts", 402_118],
  ["cart_products", 1_880_420],
  ["addresses", 93_012],
  ["otp_codes", 5_120_033],
  ["devices", 610_040],
];

export const e2Snapshot: SchemaSnapshot = {
  tables: [
    E2_USERS,
    ...OTHERS.map(([name, n], i) =>
      table(16_002 + i, name, [id, col("user_id", "bigint", 2), createdAt], n),
    ),
  ],
  foreign_keys: [],
  functions: [],
  schemas: ["public"],
  indexes: [],
  enums: [],
  sequences: [],
  extensions: [],
  server_version_num: 160_004,
};

// ---- the rows --------------------------------------------------------------

const NAMES = [
  "Ada Lovelace",
  "Grace Hopper",
  "Linus Pauling",
  "Mary Jackson",
  "Edwin Hubble",
  "Rosalind Franklin",
  "Alan Turing",
  "Katherine Johnson",
  "Tim Berners-Lee",
  "Hedy Lamarr",
  "Barbara Liskov",
  "Dennis Ritchie",
  "Margaret Hamilton",
  "Ken Thompson",
];

const pad = (n: number) => String(n).padStart(2, "0");

export const E2_ROWS: (string | null)[][] = NAMES.map((n, i) => [
  String(1001 + i * 7),
  `${n.toLowerCase().replace(/[^a-z]+/g, ".")}@example.com`,
  n,
  i % 3 !== 1 ? "true" : "false",
  `2026-09-${pad(3 + (i % 12))} ${pad(8 + ((i * 3) % 14))}:${pad((i * 17) % 60)}`,
]);

const meta = (name: string, attnum: number, typeOid: number): ColumnMeta => ({
  name,
  type_oid: typeOid,
  table_oid: E2_USERS.table_oid,
  attnum,
});

export const E2_COLUMNS: ColumnMeta[] = [
  meta("id", 1, 20),
  meta("email", 2, 25),
  meta("name", 3, 25),
  meta("is_onboarded_on_app", 4, 16),
  meta("created_at", 9, 1184),
];

/** the row the inspector is parked on, and the row the sketch's frames show
 * selected: the fourth, so the inspector header reads `row 4` */
export const E2_SEL_ROW = 3;

export const e2BrowseSql = (): string =>
  browseSql({
    table: E2_USERS,
    filters: [],
    sort: [],
    limit: 1000,
    keys: keysetKeys(E2_USERS, [], e2Snapshot.server_version_num),
  });

export const E2_READ_SQL =
  "SELECT id, email, name, is_onboarded_on_app, created_at\nFROM users\nWHERE created_at > now() - interval '7 days'\nORDER BY created_at DESC LIMIT 200;";

export const E2_WRITE_SQL =
  "UPDATE users\nSET is_onboarded_on_app = true\nWHERE email = 'ada.lovelace@example.com'\nRETURNING id;";

const statement = (sql: string, over: Partial<StatementResult> = {}): StatementResult => ({
  index: 0,
  sql,
  columns: E2_COLUMNS,
  rows: E2_ROWS.map((r) => [...r]),
  affected: null,
  ms: 38.4,
  ...over,
});

// ---- the canvas ------------------------------------------------------------

const widget = (n: number, title: string, columns: string[], rows: string[][], cell: Block["cell"]): Block => ({
  id: `e2-widget-${n}`,
  kind: "result",
  cell,
  question: title,
  prose: "",
  sql: `SELECT ${columns.join(", ")} FROM users`,
  columns,
  rows: rows.map((r) => [...r]),
  chips: [],
  status: `${rows.length} rows · ${(180 + n * 42).toFixed(1)} ms`,
  ms: 180 + n * 42,
  face: "table",
});

const e2Doc: CanvasDoc = {
  v: 2,
  blocks: [
    widget(
      1,
      "Onboarded per day",
      ["day", "onboarded"],
      [
        ["09-10", "402"],
        ["09-11", "551"],
        ["09-12", "487"],
        ["09-13", "720"],
      ],
      { x: 0, y: 0, w: 2, h: 2 },
    ),
    widget(
      2,
      "Top devices",
      ["platform", "users", "share"],
      [
        ["ios", "782", "61%"],
        ["android", "412", "32%"],
        ["web", "90", "7%"],
      ],
      { x: 2, y: 0, w: 2, h: 2 },
    ),
    {
      id: "e2-widget-note",
      kind: "note",
      cell: { x: 4, y: 0, w: 2, h: 2 },
      text: "Wednesday spike lines up with the campaign send. Check the `otp_codes` volume next.",
    },
    widget(
      3,
      "Failed OTPs · 7d",
      ["day", "sent", "failed"],
      [
        ["09-10", "18204", "312"],
        ["09-11", "19880", "287"],
        ["09-12", "23110", "1204"],
      ],
      { x: 0, y: 2, w: 2, h: 2 },
    ),
  ],
  // the sketch's own arrangement: two results and the note across the top, the
  // third result opening the next row, so the order the front reaches them is
  // legible in BOTH axes. Eight columns is what the canvas affords at 1280
  // with the side pane closed, so nothing reflows out of that shape there
  lastColumns: 8,
};

/** what a canvas widget's refetch reads back, by the SQL it sends.
 * `refreshWidget` goes through `execute`, and a shim that answered it with no
 * columns would draw the FAILED refetch — the widget's own error strip — in
 * the frame that exists to show the landing. `lat` is the sketch's own
 * 800 + 140 per widget, which staggers the landings the way the band's front
 * already staggers the starts */
export interface E2WidgetResult {
  /** the block the SQL belongs to, so the shim's log can say WHICH widget a
   * refetch was for and a timing assertion can name it */
  id: string;
  columns: ColumnMeta[];
  rows: (string | null)[][];
  lat: number;
  ms: number;
}

export function e2WidgetResult(sql: string): E2WidgetResult | null {
  const results = e2Doc.blocks.filter((b): b is ResultBlock => b.kind === "result");
  const i = results.findIndex((b) => b.sql === sql);
  const block = results[i];
  if (!block) return null;
  return {
    id: block.id,
    columns: (block.columns ?? []).map((name, c) => ({
      name,
      type_oid: 25,
      table_oid: 0,
      attnum: c + 1,
    })),
    rows: block.rows.map((r) => [...r]),
    lat: 800 + i * 140,
    ms: block.ms ?? 0,
  };
}

const e2CanvasMeta: CanvasMeta = {
  id: E2_CANVAS_ID,
  profileId: E2_PROFILE_ID,
  title: "Canvas 1",
  updatedAt: "2026-09-16T10:20:00Z",
};

// ---- the seed --------------------------------------------------------------

export interface E2Seed {
  /** the tab the state's act runs against */
  activeTabId: string;
  tabs: Tab[];
  /** useResults.byTab */
  results: Record<string, { statements: StatementResult[]; sql: string; totalMs: number }>;
  /** the three staged edits `e2-table-staged` keeps through the gesture */
  pending: { row: number; col: number; value: string; original: string }[];
  canvases: Record<string, CanvasMeta[]>;
  docs: Record<string, CanvasDoc>;
  /** the connection answers a probe (R6's dead state is the one that does not) */
  alive: boolean;
}

const tab = (over: Partial<Tab> & Pick<Tab, "id" | "name" | "kind" | "position">): Tab => ({
  sql: "",
  saved_id: null,
  table: null,
  canvas_id: null,
  profile_id: E2_PROFILE_ID,
  ...over,
});

export function e2Seed(state: E2State): E2Seed {
  const tabs: Tab[] = [
    tab({ id: E2_TABLE_TAB, name: "users", kind: "table", position: 0, table: E2_USERS }),
    tab({ id: E2_QUERY_TAB, name: "new qwry", kind: "query", position: 1, sql: E2_READ_SQL }),
    tab({
      id: E2_CANVAS_TAB,
      name: "Canvas 1",
      kind: "canvas",
      position: 2,
      canvas_id: E2_CANVAS_ID,
    }),
  ];
  const wrote = state === "e2-query-wrote";
  const query = wrote ? E2_WRITE_SQL : E2_READ_SQL;
  if (wrote) tabs[1].sql = E2_WRITE_SQL;
  const activeTabId =
    state === "e2-query" || wrote
      ? E2_QUERY_TAB
      : state === "e2-canvas"
        ? E2_CANVAS_TAB
        : E2_TABLE_TAB;
  return {
    activeTabId,
    tabs,
    results: {
      [E2_TABLE_TAB]: {
        statements: [statement(e2BrowseSql())],
        sql: e2BrowseSql(),
        totalMs: 41.2,
      },
      [E2_QUERY_TAB]: {
        statements: [
          wrote
            ? statement(E2_WRITE_SQL, { columns: [], rows: [], affected: 1, ms: 12.6 })
            : statement(E2_READ_SQL),
        ],
        sql: query,
        totalMs: wrote ? 12.6 : 41.2,
      },
    },
    pending:
      state === "e2-table-staged"
        ? [
            { row: 1, col: 2, value: "Grace B. Hopper", original: "Grace Hopper" },
            { row: 5, col: 3, value: "true", original: "false" },
            { row: 8, col: 1, value: "tim@w3.org", original: "tim.berners.lee@example.com" },
          ]
        : [],
    canvases: { [E2_PROFILE_ID]: [e2CanvasMeta] },
    docs: { [E2_CANVAS_ID]: e2Doc },
    alive: state !== "e2-dead",
  };
}

/** The one thing a seed cannot hold: the grid's selection. It is the Grid
 * component's own React state with no store door (useSelection), so the
 * sketch's selected row is reached the way the canvas fixtures reach a menu,
 * by pressing the cell the product would be pressed on. Run BEFORE the act,
 * because a selection is part of the window the gesture arrives at, not part
 * of the gesture (R4: the selected row is what must survive). */
export async function e2AfterMount(state: E2State): Promise<void> {
  if (state === "e2-canvas" || state === "e2-query-wrote") return;
  const cell = document.querySelector<HTMLElement>(
    `.vgrid-cell[data-r="${E2_SEL_ROW}"][data-c="1"]`,
  );
  cell?.dispatchEvent(new MouseEvent("mousedown", { bubbles: true, button: 0 }));
  window.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
  await new Promise<void>((r) => requestAnimationFrame(() => r()));
}
